apps/lyricsMaker/urls.py
from django.conf.urls import url
from views import Welcome, Songs, Library

app_name = 'lyricsMaker'

urlpatterns = [
    url(r'^$', Welcome.as_view(), name='index'),
    url(r'song$', Songs.as_view(), name='song'),
    url(r'library$', Library.as_view(), name='library'),
]

lyricsGenerator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.lyricsMaker.models import Song

class SongAdmin(admin.ModelAdmin):
    pass

admin.site.register(Song, SongAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.lyricsMaker.urls')),
]

apps/lyricsMaker/models.py
from __future__ import unicode_literals
from django.db import models
# from django.forms import ModelForm

# Create your models here.

class SongManager(models.Manager):
    def validate(self, postData):
        messages = []
        flag = False

        if not postData['genre'] or not postData['subj'] or not  postData['pronouns']:
            flag = True
            messages.append('Please fill in all fields !')

        if not flag:
            song = Song.objects.create(genre=postData['genre'], subj=postData['subj'], pronouns=postData['pronouns'])

            return(True, song)

        else:
            return(False, messages)

class Song(models.Model):
    genre = models.CharField(max_length=45)
    subj = models.CharField(max_length=45)
    pronouns = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = SongManager()

# class Mood(models.Model):
    # def moodPicker(self, request):
    #     mood = request.POST['subj']
    #     if mood == 'happy':
    #
    #         return True

apps/lyricsMaker/forms.py
from django import forms
# from .models import Song

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['genre', 'subj', 'pronouns']
        widgets
    def save(self, commit=True):
        song = super(SongForm, self).save(commit=False)
        song.genre = self.cleaned_data['genre']
        song.subj = self.cleaned_data['subj']
        song.pronouns = self.cleaned_data['pronouns']
        if commit:
            song.save()
        return song

apps/lyricsMaker/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.views.generic import View
from .models import Song
from django.http import HttpResponse

# Create your views here.
class Welcome(View):
    def get(self, request):
        songs = Song.objects.all()
        print '*'*20
        print len(songs)

        return render(request, 'lyricsMaker_templates/index.html')

    def post(self, request):
        postData = {
            'genre': request.POST.get('genre'),
            'subj': request.POST.get('subject'),
            'pronouns': request.POST.get('pronouns'),
        }

        result = Song.objects.validate(postData)

        if result[0]:
            print '*'*20
            print result[0], result[1]
            request.session['song_id'] = result[1].id
            song_obj = result[1]

            context = {
                'song_obj': song_obj
            }
            return HttpResponse('Submitted. Thanks for your idea! It belongs to us now.')

        else:
            for err in range(len(result[1])):
                messages.error(request, result[1][err])
            return redirect('/')

class Songs(View):
    def get(self, request):
        song = Song.objects.get(id=3)

        context = {
            'song': song,
        }
        return render(request, 'lyricsMaker_templates/lyrics.html', context)
    def post(self, request):

        song = Song.objects.get(id=1)

        context = {
            'song': song,
        }
        return render(request, 'lyricsMaker_templates/lyrics.html', context)

class Library(View):
    def get(self, request):
        songs = Song.objects.all()

        context = {
            'songs': songs,
        }

        return render(request, 'lyricsMaker_templates/library.html', context)
        
    def post(self, request):
        songs = Song.objects.all()

        context = {
            'songs': songs,
        }

        return render(request, 'lyricsMaker_templates/library.html', context)

apps/lyricsMaker/templates/lyricsMaker_templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>i got feels</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'lyricsMaker_static/css/style.css' %}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'lyricsMaker_static/js/script.js' %}"></script>
</head>

<body>
    <div id="home_wrapper">
        <div id="header">
            <h1>You've got a lot of feels.</h1>
            <h1>Write a song about it.</h1>
        </div>
        <div id="main_content">
            {% if messages%}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form class="building_blocks" action="{% url 'lyricsMaker:index' %}" method="post">
                {% csrf_token %}
                <select class="genres" name="genre">
                        <option selected disabled>Genre</option>
                        <option value="hiphop" name="genre">Hip Hop</option>
                        <option value="metal" name="genre">Metal</option>
                        <option value="pop" name="genre">Pop</option>
                        <option value="punk rock" name="genre">Punk Rock</option>
                        <option value="country" name="genre">Country</option>
                    </select>
                <select class="subject" name="subject">
                        <option selected disabled>Subject Matter</option>
                        <option name="subject" value="love">Love</option>
                        <option name="subject" value="break_ups">Break-ups</option>
                        <option name="subject" value="politics">Politics</option>
                    </select>
                <label for="pronouns">Who's it about?</label>
                <input type="text" name="pronouns" placeholder="ex: Susan, Dumbledore" size="35">
                <p><input type="submit" value="make music"></p>
            </form>
            <form class="" action="/library" method="post">
                {% csrf_token %}
                <input type="submit" value="give me ideas">
            </form>
            <br>
            <div class='to_bey'>
                <form class="" action="/song" method="post">
                    {% csrf_token %}
                    <input type="submit" name="" value="Not now, take me to Bey">
                </form>
            </div>
        </div>

    </div>
</body>

</html>

apps/lyricsMaker/templates/lyricsMaker_templates/library.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>i got feels | library</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'lyricsMaker_static/css/style.css' %}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'lyricsMaker_static/js/script.js' %}"></script>
</head>

<body>
    <div id="wrapper">
        <div id="main_content">
            <a href="/">home</a> |
            <a href="/song">bey</a>
            <h1>music library</h1>
            <div class="songs">
                {% for song in songs%}
                <div class="song">
                    <p>Genre: <em>{{song.genre}}</em></p>
                    <p>Topic: <em>{{song.subj}}</em></p>
                    <p>Who's it about? <em>{{song.pronouns}}</em></p>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</body>

</html>

apps/lyricsMaker/templates/lyricsMaker_templates/lyrics.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>i got feels | queen bey's page</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'lyricsMaker_static/css/style.css' %}">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="{% static 'lyricsMaker_static/js/script.js' %}"></script>
    </head>
    <body>
        <div id="wrapper">
            <!-- <div class="song">
                <p>{{song.genre}}</p>
                <p>{{song.subj}}</p>
                <p>{{song.pronouns}}</p>
            </div> -->
            <div id="bey_songs">
                <a href="/">home</a> |
                <a href="/library">library</a>
                <h2>show me bey</h2>
                <form class="bey_moods">
                    <select id='mood'>
                        <option selected disabled>current mood</option>
                        <option value="happy">happy</option>
                        <option value="dancey">dancey</option>
                        <option value="sad">sad</option>
                        <option value="vengeful">vengeful</option>
                        <option value="loving">loving</option>
                        <input type="submit" name="" value="get it">
                    </select>
                </form>
                <div class="player">

                </div>
            </div>
        </div>
    </body>
</html>